[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.5"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_WEBPACK_USEPOLLING = "1"
  NEXT_SHARP_PATH = "/tmp/node_modules/sharp"
  NEXT_PUBLIC_FORCE_SWAP_TO_PRERELEASE = "false"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/sharp/**/*"]
