[build]
  command = "npm install --legacy-peer-deps && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.5"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
